app/models/Mesas.py
from . import db

class Mesa(db.Model):
    __tablename__ = 'mesas'
    id_mesa = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(50), nullable=False)

app/routes/admin.py
import bcrypt
from flask import Blueprint, render_template, redirect, request, url_for, session
from ..models.Usuario import Usuario
from ..models.Mesas import Mesa
from ..models.Notas import Nota
from ..models.Comidas import Comida, db
from ..models.ingredientes_plato import ingredientes_plato
from ..models.Ingredientes import Ingrediente
from ..models.Usuario import Usuario
from ..models.Comida_nota import ComidaNota
from werkzeug.utils import secure_filename
from datetime import datetime, timedelta
import os
admin_bp = Blueprint('admin', __name__, template_folder='../templates/')

# Carpeta donde se guardarán las imágenes
CARPETA_IMG = 'app/static/img'
# Extensiones permitidas
EXTENSIONES = {'png', 'jpg', 'jpeg', 'gif'}

def Comprobar_Archivo(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in EXTENSIONES

# zona Comida
@admin_bp.route("/lista_comida")
def lista_comida():
    if "user" not in session:
        return redirect(url_for("auth.login"))
    comidas = Comida.query.all()
    ingredientes = Ingrediente.query.all()
    
    for comida in comidas:
        #obtener los ingredientes por comidas
        comida.ingredientes = ingredientes_plato.query.filter(ingredientes_plato.id_comida == comida.id_comida).all()
        comida.ingredientes_ids = [i.id_ingrediente for i in comida.ingredientes]

    return render_template("listaComida.html", comidas=comidas, ingredientes=ingredientes)

# metodo para crear comida
@admin_bp.route("/lista_comida/crear_comida", methods=['POST'])
def crear_comida():
    if request.method == 'POST':
        nombreComida = request.form.get("comidaNombre")
        Alias = request.form.get("Alias")
        precio = request.form.get("precio", 0)
        tipo = request.form.get("TipoComida")
        archivo = request.files.get('imagen')
        nombreArchivo = ""
        ruta_completa = ""
        #crea el archivo si no existe 
        if archivo and Comprobar_Archivo(archivo.filename):
            nombreArchivo = secure_filename(archivo.filename)
            ruta_completa = os.path.join(CARPETA_IMG, nombreArchivo)
            if not os.path.exists(ruta_completa):
                archivo.save(ruta_completa)
        nuevaComida = Comida(
            nombre = nombreComida,
            alias = Alias,
            tipo = tipo,
            precio = precio,
            imagen = f"img/{nombreArchivo}"
        )
        db.session.add(nuevaComida)
        db.session.commit()
        
    return redirect(url_for("admin.lista_comida"))

#metodo para elimar la comida
@admin_bp.route("/lista_comida/eliminar_comida/<int:id_comida>" , methods=['POST'])
def eliminar_comida(id_comida):
    if request.method == 'POST':
        #cojemos la comida en cuestion
        comida = Comida.query.filter(Comida.id_comida == id_comida).first()
        # cojemos los ingredientes asignados y tambien los eliminamos
        comida_ing = ingredientes_plato.query.filter(ingredientes_plato.id_comida == id_comida).all()
        for ig in comida_ing:
            db.session.delete(ig)
        db.session.delete(comida)
        db.session.commit()
    return redirect(url_for("admin.lista_comida"))

#metodo para editar los valores de la comida
@admin_bp.route("/lista_comida/editar_comida/<int:id_comida>", methods=['POST'])
def editar_comida(id_comida):
    if request.method == 'POST':
        # coge la comida en cuestion
        comida = Comida.query.filter(Comida.id_comida == id_comida).first()
        if comida:
            nombreComida = request.form.get("comidaNombre")
            Alias = request.form.get("Alias")
            precio = request.form.get("precio", 0)
            tipo = request.form.get("TipoComida")
            archivo = request.files.get('imagen')
            nombreArchivo = ""
            ruta_completa = ""
            #crea el archivo si no existe 
            if archivo and Comprobar_Archivo(archivo.filename):
                nombreArchivo = secure_filename(archivo.filename)
                ruta_completa = os.path.join(CARPETA_IMG, nombreArchivo)
                if not os.path.exists(ruta_completa):
                    archivo.save(ruta_completa)

            comida.nombre = nombreComida
            comida.alias = Alias
            comida.tipo = tipo
            comida.precio =precio
            if comida.imagen != ruta_completa and ruta_completa != "":
                comida.imagen = f"img/{nombreArchivo}"
            db.session.commit()
        
    return redirect(url_for("admin.lista_comida"))

@admin_bp.route("/lista_comida/AnadirIngredientes/<int:id_comida>", methods=['POST'])
#metodo para añafir ingredientes al plato
def anadir_ingredientes_plato(id_comida):
    if request.method == 'POST':
        ingredientes = request.form.getlist('ingredientes[]')
        print(ingredientes)
        print(id_comida)
        #cogemos los que ya tenia y los eliminamos para volver a crearlos
        ip = ingredientes_plato.query.filter(ingredientes_plato.id_comida == id_comida).all()
        for i in ip:
            db.session.delete(i)
            db.session.commit()
        for ingrediente in  ingredientes:
            print(ip)
            nuevoIngredientePlato = ingredientes_plato (
                id_comida = id_comida,
                id_ingrediente = ingrediente
            )
            db.session.add(nuevoIngredientePlato)
            db.session.commit()
    return redirect(url_for("admin.lista_comida"))

#zona resumen
@admin_bp.route("/resumen", methods=['POST','GET'])
def resumen():
    if "user" not in session:
        return redirect(url_for("auth.login"))
    desde_str = request.form.get("desde")
    hasta_str = request.form.get("hasta")

    # Procesar fechas con valores por defecto si no se envían
    if desde_str:
        desde = datetime.strptime(desde_str, "%Y-%m-%d")
    else:
        desde = datetime.now()

    if hasta_str:
        hasta = datetime.strptime(hasta_str, "%Y-%m-%d")
    else:
        hasta = desde + timedelta(days=30)
    #cogemos las nostas entre las dos fechas
    notas = Nota.query.filter(Nota.fecha >= desde, Nota.fecha <= hasta).all()
    #total de notas
    total_notas = len(notas)
    dinero_total = 0
    for nota in notas:
        #cogemos todas los "platos" por nota
        comidas_nota = ComidaNota.query.filter(ComidaNota.id_nota == nota.id_nota).all()
        for cn in comidas_nota:
            dinero_total=dinero_total + cn.precio
    
    promedio_mesa = round(dinero_total / int(total_notas), 2) if total_notas > 0 else 0
    return render_template("resumen.html", promedio_mesa=promedio_mesa, total_notas=total_notas, dinero_total=dinero_total, desde=desde_str, hasta=hasta_str )




# Zona MESAS
@admin_bp.route("/lista_mesas")
#metodo que abre la pestaña de mesas
def lista_mesas():
    if "user" not in session:
        return redirect(url_for("auth.login"))
    mesas = Mesa.query.order_by(Mesa.nombre).all() #coge las mesas y las ordena segun el nombre
    return render_template("listaMesas.html", mesas=mesas)

@admin_bp.route("/lista_mesas/editar/<int:id_mesa>", methods=['POST'])
#metodo para editar mesas
def editar_mesa(id_mesa):
    if request.method == "POST":
        #coje la mesa en cuestion
        mesa = Mesa.query.filter(Mesa.id_mesa==id_mesa).first()
        if mesa:
            #cogemos los valores
            nombreMesa = request.form.get("nombreMesa")
            #buscamos la mesa
            #cambiamos el nombre
            mesa.nombre = nombreMesa

            db.session.commit() #guardamos los cambios

    return redirect(url_for("admin.lista_mesas"))

@admin_bp.route("/lista_mesas/añadir", methods=['POST'])
#metodo para crear mesas
def Añadir_mesa():
    if request.method == "POST":
        nombreMesa = request.form.get("nombreMesa")
        #nueva mesa
        nuevaMesa = Mesa(nombre=nombreMesa) #creamos la nueva mesa

        db.session.add(nuevaMesa) 
        db.session.commit() #guardamos los cambios
    return redirect(url_for("admin.lista_mesas"))

#metodo para eliminar mesas
@admin_bp.route("/lista_mesas/eliminar/<int:id_mesa>", methods=['POST'])
def delete_mesas(id_mesa):
    if request.method == "POST":
        #coje la mesa en cuestion
        mesa = Mesa.query.filter(Mesa.id_mesa==id_mesa).first()
        if mesa:
            db.session.delete(mesa)
            db.session.commit()
    return redirect(url_for("admin.lista_mesas"))


#Zona de ingredientes
@admin_bp.route("/lista_ingredientes")
#metodo que abre la pestaña de mesas
def lista_ingredientes():
    if "user" not in session:
        return redirect(url_for("auth.login"))
    ingredientes = Ingrediente.query.all() #coge todos los ingredientes
    return render_template("listaIngredientes.html", ingredientes=ingredientes)

@admin_bp.route("/lista_ingredientes/editar/<int:id_ingrediente>", methods=['POST'])
#metodo para editar mesas
def editar_ingredientes(id_ingrediente):
    if request.method == "POST":
        ingrediente = Ingrediente.query.filter(Ingrediente.id_ingrediente==id_ingrediente).first()
        if ingrediente:
            #cogemos los valores
            nombreIngrediente = request.form.get("nombreIngrediente")
            #cambiamos el nombre
            ingrediente.nombre = nombreIngrediente

            db.session.commit() #guardamos los cambios

    return redirect(url_for("admin.lista_ingredientes"))
#meto para añadir ingredientes
@admin_bp.route("/lista_ingredientes/añadir", methods=['POST'])
def Añadir_ingrediente():
    if request.method == "POST":
        nombreIngrediente = request.form.get("nombreIngrediente")
        #nuevo ingrediente
        nuevoIngrediente = Ingrediente(nombre=nombreIngrediente) #creamos el ingrediente

        db.session.add(nuevoIngrediente) 
        db.session.commit() #guardamos los cambios
    return redirect(url_for("admin.lista_ingredientes"))
# metodo para eliminar ingredientes
@admin_bp.route("/lista_ingredientes/eliminar/<int:id_ingrediente>", methods=['POST'])

app/routes/auth.py
from flask import Blueprint, render_template, redirect, url_for, session, request
from ..models.Usuario import Usuario
auth_bp = Blueprint('auth', __name__, template_folder='../templates/')
import bcrypt

@auth_bp.route('/', methods=["GET", "POST"])
def login():
    if "user" in session:
        return redirect(url_for('dashboard.Dashboard_mesas'))

    if request.method == "POST":
        #cojemos los valores del form 
        email = request.form["email"]
        contrasena = request.form["contrasena"]
        # buscamos al usuario
        usuario_encontrado = Usuario.query.filter_by(email=email).first()
        # si el usuario existe y las contraseñas coinciden se crean las variables de sesion y se pasa a la pagina de mesas
        if usuario_encontrado and bcrypt.checkpw(contrasena.encode("utf-8"), usuario_encontrado.contrasena.encode("utf-8")):
            session["user"] = usuario_encontrado.id_usuario
            session["is_admin"] = usuario_encontrado.is_Admin
            user_id = session["user"]

            return redirect(url_for("dashboard.Dashboard_mesas"))
        # si te equivocas se vuelve a abrir el login pero con un error
        return render_template("login.html", error="Credenciales incorrectas")
    
    return render_template("login.html")

app/routes/dashboard.py
from flask import Blueprint, render_template, redirect, request, url_for, session

from ..models.ingredientes_plato import ingredientes_plato
from ..models.Usuario import Usuario
from ..models.Mesas import Mesa
from ..models.Notas import Nota, db
from ..models.Comida_nota import ComidaNota
from ..models.Comidas import Comida
from ..models.Ingredientes import Ingrediente
from datetime import datetime
dashboard_bp = Blueprint('dashboard', __name__, template_folder='../templates/')
#metodo que abre la pestaña de mesas
@dashboard_bp.route('/mesas')
def Dashboard_mesas():
    if "user" not in session:
        return redirect(url_for("auth.login"))
    usuario = Usuario.query.first()
    mesas = Mesa.query.order_by(Mesa.nombre).all() #coge las mesas y las ordena segun el nombre
    return render_template('mesas.html', Mesas=mesas ,usuario=usuario)

#Abre la ventana para añadir "platos" a la nota
@dashboard_bp.route('/comida_bebida/<int:id_nota>')
def comida_bebida(id_nota):
    if "user" not in session:
        return redirect(url_for("auth.login"))
    #obtenemos la comida y ingredientes
    comidas = Comida.query.all()
    ingredientes = Ingrediente.query.all()
    for comida in comidas:
         #cogemos los ingredientes de la comida y lo guardamos como un atributo
         comida.ingredientes = ingredientes_plato.query.filter(ingredientes_plato.id_comida == comida.id_comida).all()
         comida.ingredientes_ids = [i.id_ingrediente for i in comida.ingredientes]
            
    return render_template("comidaBebida.html", id_nota=id_nota, comidas=comidas, ingredientes=ingredientes)    

#metodo que añade la nueva comida seleccionada a la nota
@dashboard_bp.route('/comida_bebida/anadire/<int:id_nota>/<int:id_comida>', methods=['POST'])
def anadir_comida_nota(id_nota, id_comida):
    if request.method == 'POST':
        cantidad = request.form.get("cantidad")
        ingredientes = request.form.getlist("ingredientes[]")
        #buscamos la comida
        comida = Comida.query.filter(Comida.id_comida == id_comida).first()
        ingrediente_comida = Ingrediente.query.filter(Ingrediente.id_ingrediente == comida.id_comida).all()
        nombre=comida.nombre
        print(nombre)
        # modificamos el nombre para que contenga los ingredientes restantes de la comida
        if ingredientes:
                for ing in ingredientes:
                    nombre = nombre + " " +  ing
        nueva_nota_comida = ComidaNota(
            id_nota = id_nota,
            id_comida = id_comida,
            nombre = nombre,
            cantidad = cantidad,
            checked = False,
            precio = comida.precio
        )
        db.session.add(nueva_nota_comida)
        db.session.commit()


    return redirect(url_for("dashboard.abrir_nota", id_nota=id_nota))

#metodo para elimanar una comida de la comanda
@dashboard_bp.route("/delete/comida_nota/<int:id_comida_nota>/<int:id_nota>" , methods=['POST'])
def delete_comida_nota(id_comida_nota,id_nota):
    if request.method == 'POST':
         #obtenemos la nota/comida para cambiar el estado
        comida_nota =  ComidaNota.query.filter(ComidaNota.id_comida_nota == id_comida_nota).first()
        db.session.delete(comida_nota)
        db.session.commit()
    return redirect(url_for("dashboard.abrir_nota", id_nota=id_nota))

#metodo que nos permite marcar como terminado o falta, las comidas de la nota
@dashboard_bp.route('/check/<int:id_comida_nota>/<int:id_nota>' , methods=['POST'])
def check_comida(id_comida_nota, id_nota):
    if request.method == 'POST':
        #obtenemos la nota/comida para cambiar el estado
        comida_nota =  ComidaNota.query.filter(ComidaNota.id_comida_nota == id_comida_nota).first()
        print(comida_nota)
        if comida_nota.checked == 1:
            comida_nota.checked = 0
        else:
            comida_nota.checked = 1
        db.session.commit()
    return redirect(url_for("dashboard.abrir_nota", id_nota=id_nota))

# metod que habre la ventana de la nota especifica
@dashboard_bp.route('/nota_especifica/<int:id_nota>')
def abrir_nota(id_nota):
    if "user" not in session:
        return redirect(url_for("auth.login"))
    # buscamos la nota activa de la mesa
    nota = Nota.query.filter(Nota.id_nota == id_nota, Nota.is_Active == 1).first()
    #obtenemos la mesa 
    mesa = Mesa.query.filter(Mesa.id_mesa == nota.id_mesa).first()
    #obtener todos los registros de comida de la nota
    nota_comida = ComidaNota.query.filter(ComidaNota.id_nota == nota.id_nota).all()


    return render_template("nota_especifica.html", mesa=mesa, nota=nota, nota_comida=nota_comida)

#metodo que crea la nota y nos redirije a la ventana de dicha nota
@dashboard_bp.route('/crear_nota/<int:id_mesa>')
def crearNota(id_mesa):
        if "user" not in session:
            return redirect(url_for("auth.login"))
    # buscamos la nota activa de la mesa
        nota = Nota.query.filter(Nota.id_mesa == id_mesa, Nota.is_Active == 1).first()
        #
        if not nota or nota.id_nota == 99 :
            nueva_nota = Nota(
                id_mesa=id_mesa,
                fecha= datetime.now(),
                is_Active = 1
            )
            db.session.add(nueva_nota)
            db.session.commit()
            id_generado = nueva_nota.id_nota
            return redirect(url_for("dashboard.abrir_nota", id_nota=id_generado))
        else:
            return redirect(url_for("dashboard.abrir_nota", id_nota=nota.id_nota))

# funcion que hace que la nota pase a estar desactivada y asi dar paso a otra
@dashboard_bp.route('/jubilar_nota/<int:id_nota>')
def jubilar_nota(id_nota):
        nota = Nota.query.filter(Nota.id_nota == id_nota, Nota.is_Active == 1).first()
        if nota:
            nota.is_Active = 0
            db.session.commit()
        return redirect(url_for("dashboard.Dashboard_mesas"))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Thais</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">
    <link
    href="{{ url_for('static', filename='css/base.css') }}"
    rel="stylesheet"
    />
    <link
    href="{{ url_for('static', filename='css/tabla.css') }}"
    rel="stylesheet"
    />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css" />
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>
</head>
<body>
    <nav id="navThais">
        <img id="logothais" src="{{ url_for('static', filename='img/ThaisLogo.png') }}" alt="">
        <div id="navlinks">
            <div><h2><a class="colorBlanco subreayadoDinamico" href="{{ url_for('dashboard.Dashboard_mesas') }}">Mesas</a></h2></div>
        </div>
        <div class="selector-container">
            {% if session.get("is_admin") %}
            <!-- hacer que se oculte con lo de admin -->
            <select id="selector" onchange="redirigir()">
                <option value="">-- Zona Admin --</option>
                <option value="{{ url_for('admin.lista_comida') }}">Comida y bebida</option>
                <option value="{{ url_for('admin.lista_mesas') }}">Gestion Mesas</option>
                <option value="{{ url_for('admin.lista_ingredientes') }}">Ingredientes</option>
                <option value="{{ url_for('admin.lista_Usuarios') }}">Usuarios</option>
                <option value="{{ url_for('admin.resumen') }}">Resumen</option>
            </select>
            {% endif %}
        </div>
    </nav>
    <div class="contenedorCentro">

        {% block content %}{% endblock %}
    
    </div>

   
</body>
<script>
    function redirigir() {
        const seleccion = document.getElementById('selector').value;
        if (seleccion) {
            window.location.href = seleccion;
            
        }
    }
</script>
</html>

app/templates/crear_nota.html
{% extends "base.html" %}
{% block title %}Crear Nota{% endblock %}
{% block content %}

{{id_mesa}} {{nombreMesa}}


{% endblock %}

app/templates/hola.html
patata

app/templates/listaComida.html
{% extends "base.html" %}
{% block title %}Lista Comida y bebida{% endblock %}
{% block content %}
<link href="{{ url_for('static', filename='css/modal.css') }}" rel="stylesheet" />

<div class="tituloPagina">
  <b>
    Comida y bebida
  </b>
</div>
<!-- Botón para abrir el modal -->
<button data-target="modalAñadir" onclick="abrirModal(event)" class="boton guardar botonAnadir">Añadir</button>

<!-- Modal -->
<div id="modalAñadir" class="modal">
  <div class="modal-content">
    <form method="post" action="{{ url_for('admin.crear_comida')}}" enctype="multipart/form-data">
      <label for="comidaNombre">Nombre comida o bebida:</label>
      <input type="text" id="comidaNombre" name="comidaNombre" required>

      <label for="Alias">Alias:</label>
      <input type="text" id="Alias" name="Alias" required>

      <label for="precio">Precio:</label>
      <input type="text" id="precio" name="precio" required>
      <label for="TipoComida">Selecciona Tipo</label>
      <select name="TipoComida" id="TipoComida">
        <option value="Comida">Comida</option>
        <option value="Bebida">Bebida</option>
      </select>
      <label for="imagen">Imagen:</label>
      <input type="file" name="imagen" >

      <div class="modal-buttons">
        <button class="boton guardar" type="submit">Guardar</button>
        <button class="boton cerrar" data-target="modalAñadir" onclick="cerrarModal(event)"
          type="button">Cerrar</button>
      </div>
    </form>
  </div>
</div>



<div class="table-container">
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Alias</th>
        <th>Precio</th>
        <th>Tipo</th>
        <th>Ingredientes</th>
        <th>Acciones</th>
      </tr>
    </thead>
    <tbody>
      {%for comida in comidas%}
      <tr>
        <td>{{comida.nombre}}</td>
        <td>{{comida.alias}}</td>
        <td>{{comida.precio}}</td>
        <td>{{comida.tipo}}</td>
        <td> 
          <div class="contenedorAcciones">
          <button data-target="modalIngredientes{{comida.id_comida}}" onclick="abrirModal(event)" class="boton guardar ">Ingredientes</button></td>
        </div>
        <td>
          <div class="contenedorAcciones">
            <button data-target="modalEditar{{comida.id_comida}}" id="editar{{comida.id_comida}}"
              onclick="abrirModal(event)" class="botonAcciones botonAzul">
              <i class="fa fa-edit"></i>
            </button>
            <form action="{{ url_for('admin.eliminar_comida', id_comida=comida.id_comida) }}" method="post">
              <button type="submit" class="botonAcciones botonRojo">
                <i class="fa fa-trash"></i>
              </button>
            </form>
        </td>
      </tr>
      {%endfor%}
    </tbody>
  </table>
</div>

{%for comida in comidas%}
<div id="modalEditar{{comida.id_comida}}" class="modal">
  <div class="modal-content">
    <form method="post" action="{{ url_for('admin.editar_comida', id_comida=comida.id_comida)}}" enctype="multipart/form-data">
      <input type="hidden" id="tipo" name="tipo" value="Comida">
      <label for="comidaNombre">Nombre comida o bebida:</label>
      <input value="{{comida.nombre}}" type="text" id="comidaNombre" name="comidaNombre" required>

      <label for="Alias">Alias:</label>
      <input value="{{comida.alias}}" type="text" id="Alias" name="Alias" required>

      <label for="precio">Precio:</label>
      <input  value="{{comida.precio}}" type="text" id="precio" name="precio" required>
      <select value="{{comida.tipo}}" name="TipoComida" id="TipoComida">
        <option value="Comida">Comida</option>
        <option value="Bebida">Bebida</option>
      </select>
      <label for="imagen">Imagen:</label>
      <input type="file" name="imagen">

      <div class="modal-buttons">
        <button class="boton guardar" type="submit">Guardar</button>
        <button class="boton cerrar" data-target="modalEditar{{comida.id_comida}}" onclick="cerrarModal(event)"
          type="button">Cerrar</button>
      </div>
    </form>
  </div>
  </div>
    <div id="modalIngredientes{{comida.id_comida}}" class="modal">
  <div class="modal-content">
    <form method="post" action="{{ url_for('admin.anadir_ingredientes_plato', id_comida=comida.id_comida)}}">
        <label for="multiSelectAñadir">Selecciona varias opciones:</label>
        <select id="multiSelectAñadir" name="ingredientes[]" multiple>
          {%for ingrediente in ingredientes%}
          {% if ingrediente.id_ingrediente in comida.ingredientes_ids  %}
          <option selected value="{{ingrediente.id_ingrediente}}">{{ingrediente.nombre}}</option>
          {% else %}
          <option value="{{ingrediente.id_ingrediente}}">{{ingrediente.nombre}}</option>
          {% endif %}
          {%endfor%}
        </select>
      <div class="modal-buttons">
        <button class="boton guardar" type="submit">Guardar</button>
        <button class="boton cerrar" data-target="modalIngredientes{{comida.id_comida}}" onclick="cerrarModal(event)"
          type="button">Cerrar</button>
      </div>
    </form>
  </div>
  </div>

  {%endfor%}
  <!-- Script para manejar el modal -->
  <script>
    function abrirModal(event) {
      const id = event.target.dataset.target;
      document.getElementById(id).style.display = 'flex';
    }
    function cerrarModal(event) {
      const id = event.target.dataset.target;
      document.getElementById(id).style.display = 'none';
    }
  // Esto me permite tener el multi selector en varios modales al mismo tiempo
  document.addEventListener("DOMContentLoaded", function () {
    document.querySelectorAll("select[id^='multiSelectAñadir']").forEach(function (select) {
      new Choices(select, {
        removeItemButton: true,
        placeholderValue: 'Selecciona opciones...',
        searchEnabled: false
      });
    });
  });
  </script>

  {% endblock %}

app/templates/mesas.html
{% extends "base.html" %}
{% block title %}Mesas{% endblock %}
{% block content %}
    <div class="contenedorCagitas">
        {% for mesa in Mesas%}
        {% if mesa.id_mesa != 99%}
        <a class="tamañoletara3  colorrojo subreayadoDinamico" href="{{ url_for('dashboard.crearNota', id_mesa=mesa.id_mesa) }}"><div class="cajitas"><b><h3>{{mesa.nombre}}</h3></b></div></a>
        {% endif %}
        {% endfor %}
    
    </div>
    <div class="tituloPagina">
        <b><a class=" colorrojo subreayadoDinamico" href="{{ url_for('dashboard.crearNota', id_mesa=99, nombre='Para llevar') }}">Para llevar</a></b>
    </div>





{% endblock %}

app/templates/nota_especifica.html
{% extends "base.html" %}
{% block title %}Calendario Dieta{% endblock %}
{% block content %}
<link
href="{{ url_for('static', filename='css/modal.css') }}"
rel="stylesheet"
/>

<div class="tituloPagina">
    <b>
         Mesa: {{mesa.nombre}}
    </b>
</div>
<a  href="{{ url_for('dashboard.comida_bebida', id_nota=nota.id_nota )}}" class="boton guardar botonAnadir">Añadir</a>
<div class="table-container">
    <table>
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>¿hecho?</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            {%for comida in nota_comida%}
            <tr>
                <td>{{comida.nombre}}</td>
                <td>{{comida.cantidad}}</td>
                <td>
                    {% if comida.checked == 1 %}
                    Terminado
                    {% else %}
                    Falta
                    {% endif%}
                </td>
                <td>
                    <div class="contenedorAcciones">
                        <form action="{{ url_for('dashboard.check_comida', id_comida_nota=comida.id_comida_nota, id_nota=nota.id_nota) }}"  method="post">
                            <button type="submit" class="botonAcciones botonVerde">
                                <i class="fa fa-check"></i>
                            </button>
                        </form>
                        <form action="{{ url_for('dashboard.delete_comida_nota',  id_comida_nota=comida.id_comida_nota, id_nota=nota.id_nota) }}" method="post">
                            <button type="submit" class="botonAcciones botonRojo">
                                <i class="fa fa-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
            {%endfor%}
        </tbody>
    </table>

</div>
<a  href="{{ url_for('dashboard.jubilar_nota', id_nota=nota.id_nota )}}" class="boton eliminar botonAnadir">Desactivar</a>


{% endblock %}